import test from 'node:test';
import assert from 'node:assert/strict';
import {Game,STEP,islands} from '../src/game.js';
function step(g,n,input={x:0,z:0,rise:false}){for(let i=0;i<n;i++)g.step(STEP,input);}
test('second jump grants at most three seconds of flight, repeated input cannot refill it',()=>{const g=new Game();g.start();g.jump();step(g,12);g.jump();assert.equal(g.player.flying,true);g.player.y=30;step(g,180,{rise:true});g.jump();step(g,180,{rise:true});assert.equal(g.player.flight,0);assert.equal(g.player.flying,false);g.jump();assert.equal(g.player.flying,false);});
test('landing resets the flight charge',()=>{const g=new Game();g.start();Object.assign(g.player,{x:0,z:0,y:.1,vy:-2,grounded:false,flying:false,spent:true,flight:0});step(g,10);assert.equal(g.player.grounded,true);assert.equal(g.player.flight,3);assert.equal(g.player.spent,false);});
test('pausing freezes world state and flight',()=>{const g=new Game();g.start();g.jump();step(g,10);g.jump();g.mode='paused';const before=JSON.stringify(g);step(g,500,{z:-1,rise:true});assert.equal(JSON.stringify(g),before);});
test('falling restores the last landed checkpoint and costs one heart',()=>{const g=new Game();g.start();g.checkpoint=3;g.player.y=-20;step(g,1);assert.equal(g.hearts,2);assert.equal(g.player.z,islands[3].z+2);assert.equal(g.player.flight,3);});
test('checkpoint requires landing, not flying over an island',()=>{const g=new Game();g.start();Object.assign(g.player,{x:islands[2].x,z:islands[2].z,y:10,grounded:false});step(g,1);assert.equal(g.checkpoint,0);Object.assign(g.player,{y:islands[2].y+.01,vy:-1});step(g,2);assert.equal(g.checkpoint,2);});
test('three kittens must be rescued before entering the treehouse',()=>{const g=new Game();g.start();const goal=islands[6];Object.assign(g.player,{x:goal.x,z:goal.z-2,y:goal.y});step(g,1);assert.equal(g.mode,'playing');g.rescued=3;step(g,1);assert.equal(g.mode,'won');});
test('rescuing a kitten and collecting a fish happens only once',()=>{const g=new Game();g.start();const k=g.kittens[0];Object.assign(g.player,{x:k.x,z:k.z,y:k.y});step(g,1);assert.equal(g.rescued,1);step(g,10);assert.equal(g.rescued,1);const f=g.pickups[0];Object.assign(g.player,{x:f.x,z:f.z,y:f.y-.7});step(g,1);const count=g.fish;step(g,10);assert.equal(g.fish,count);assert.ok(count>0);});
test('dog can be stomped from above; side contact costs a heart',()=>{const g=new Game();g.start();let d=g.dogs[0];Object.assign(g.player,{x:d.x,z:d.z,y:d.y+1.1,vy:-5,grounded:false});d.phase=Math.PI/2;d.x=islands[1].x+2.7;d.z=islands[1].z;g.player.x=d.x;g.player.z=d.z;step(g,1);assert.equal(d.alive,false);assert.ok(g.player.vy>0);g.reset();g.mode='playing';d=g.dogs[0];d.phase=0;Object.assign(g.player,{x:islands[1].x,z:islands[1].z+1.5,y:d.y});step(g,1);assert.equal(g.hearts,2);});
test('all island gaps are crossable with a jump and one flight charge',()=>{for(let i=0;i<islands.length-1;i++){const g=new Game();g.start();g.dogs=[];const a=islands[i],b=islands[i+1],dx=b.x-a.x,dz=b.z-a.z,len=Math.hypot(dx,dz),dir={x:dx/len,z:dz/len,rise:true};Object.assign(g.player,{x:a.x+dir.x*(a.r-1),z:a.z+dir.z*(a.r-1),y:a.y});g.checkpoint=i;g.jump();step(g,25,dir);g.jump();let arrived=false;for(let n=0;n<600;n++){const dist=Math.hypot(g.player.x-b.x,g.player.z-b.z);g.step(STEP,dist<2?{x:0,z:0,rise:false}:dir);if(g.checkpoint===i+1){arrived=true;break;}if(g.hearts<3)break;}assert.ok(arrived,`gap ${i} to ${i+1} must be crossable`);}});

test('Asscat faces opposite to movement in every direction',()=>{for(const [x,z] of [[0,-1],[0,1],[1,0],[-1,0],[1,-1]]){const g=new Game();g.start();step(g,5,{x,z});const p=g.player,front={x:-Math.sin(p.angle),z:-Math.cos(p.angle)};assert.ok(front.x*x+front.z*z<0,'the rear leads and the face trails');}});
test('switching levels resets progress and uses different terrain',()=>{const g=new Game();g.start(0);g.fish=10;g.rescued=3;g.start(1);assert.equal(g.level.type,'village');assert.equal(g.fish,0);assert.equal(g.rescued,0);assert.ok(g.surfaces.every(s=>s.rx));assert.ok(g.level.obstacles.length>0);g.start(2);assert.ok(g.level.wind>0);g.start(3);assert.ok(g.level.springs.length>0);});
test('village crates block walking and can be landed on',()=>{const g=new Game();g.start(1);g.dogs=[];const o=g.level.obstacles[0];Object.assign(g.player,{x:o.x,z:o.z+o.d/2+.5});step(g,60,{z:-1});assert.ok(g.player.z>o.z+o.d/2);Object.assign(g.player,{x:o.x,z:o.z,y:o.h+.1,vy:-3,grounded:false});step(g,20);assert.equal(g.player.y,o.h);assert.equal(g.player.grounded,true);});
test('canyon crosswind applies airborne but does not slide a grounded cat',()=>{const g=new Game();g.start(2);g.dogs=[];step(g,60);assert.equal(g.player.x,0);g.jump();step(g,30);assert.ok(g.player.x>.2);});
test('rooftop spring launches once and leaves flight available',()=>{const g=new Game();g.start(3);g.dogs=[];const spring=g.level.springs[0],surface=g.surfaces[spring.island];Object.assign(g.player,{x:spring.x,z:spring.z,y:surface.y});step(g,1);assert.equal(g.player.vy,14);assert.equal(g.player.grounded,false);g.jump();assert.equal(g.player.flying,true);assert.equal(g.player.flight,3);});
test('every new course has crossable transitions with the normal flight budget',()=>{for(let level=1;level<4;level++)for(let i=0;i<6;i++){const g=new Game();g.start(level);g.dogs=[];const a=g.surfaces[i],b=g.surfaces[i+1],dx=b.x-a.x,dz=b.z-a.z,len=Math.hypot(dx,dz),dir={x:dx/len,z:dz/len,rise:true};Object.assign(g.player,{x:a.x+dir.x*(a.r-1),z:a.z+dir.z*(a.r-1),y:a.y});g.checkpoint=i;g.jump();step(g,25,dir);g.jump();let arrived=false;for(let n=0;n<700;n++){const p=g.player,d=Math.hypot(p.x-b.x,p.z-b.z);g.step(STEP,d<1.7?{x:0,z:0,rise:false}:{x:(b.x-p.x)/d,z:(b.z-p.z)/d,rise:true});if(g.checkpoint===i+1){arrived=true;break;}if(g.hearts<3)break;}assert.ok(arrived,`${g.level.name} transition ${i} must be crossable`);}});
test('all levels support rescue, finish, death and checkpoint retry',()=>{for(let level=0;level<4;level++){const g=new Game();g.start(level);g.dogs=[];for(const k of g.kittens){Object.assign(g.player,{x:k.x,z:k.z,y:k.y,vy:0});step(g,1);}assert.equal(g.rescued,3);g.checkpoint=4;g.hearts=1;g.hurt(true);assert.equal(g.mode,'lost');g.retry();assert.equal(g.rescued,3);assert.equal(g.player.z,g.surfaces[4].z+2);const goal=g.surfaces[6];Object.assign(g.player,{x:goal.x,z:goal.z-2,y:goal.y,vy:0});step(g,1);assert.equal(g.mode,'won');}});
