const round=(x,z,y,r,name)=>({x,z,y,r,name});
const rect=(x,z,y,rx,rz,name)=>({x,z,y,rx,rz,r:Math.min(rx,rz),name});
export const levels=[
 {id:'gardens',name:'Floating Gardens',type:'gardens',tag:'FLIGHT SCHOOL',description:'Wide gaps, golden fish trails and a sky full of dog patrols.',hint:'Jump twice to fly. Hold to climb; release to glide.',surfaces:[round(0,0,0,8,'Whisker Meadow'),round(-3,-16,1,6,'Clover Crossing'),round(4,-32,2,6.5,'Cloudstep Canyon'),round(-3,-49,2.5,6.5,'The Wind Gardens'),round(3,-66,3,6,'Dogwatch Heights'),round(-2,-82,4,6.5,'Sunflower Reach'),round(2,-99,4,8,'Cat Haven')],obstacles:[],springs:[],sky:0xdde3ce},
 {id:'village',name:'Backstreet Bandit',type:'village',tag:'STREET-LEVEL SLALOM',description:'A grounded village run: weave through market crates and dog patrols.',hint:'Stay on the street. Jump crates or take the side lanes.',surfaces:Array.from({length:7},(_,i)=>rect(0,-i*14,0,7,7.6,['Market Gate','Fishmonger Row','Crate Alley','Village Square','Bakery Bend','Lantern Lane','The Cat Café'][i])),obstacles:[{x:-3,z:-11,y:0,w:6,d:1.5,h:1.3},{x:3,z:-23,y:0,w:6,d:1.5,h:1.6},{x:0,z:-34,y:0,w:4,d:3,h:1.3},{x:-3,z:-46,y:0,w:6,d:1.5,h:1.7},{x:3,z:-59,y:0,w:6,d:1.5,h:1.5},{x:0,z:-74,y:0,w:5,d:2,h:1.4}],springs:[],sky:0xf1dfbd},
 {id:'canyon',name:'Redrock Run',type:'canyon',tag:'LEDGES & CROSSWINDS',description:'Follow narrow sandstone ledges above a river. Watch the crosswind.',hint:'Crosswind pushes you right in the air. Steer left to compensate.',wind:1.5,surfaces:[rect(0,0,0,6,7,'Trailhead'),rect(-4,-14,1,4,5,'Copper Shelf'),rect(3,-28,2,3.5,5,'Needle Pass'),rect(-3,-42,2,4,5,'The Narrows'),rect(4,-57,3,3.5,5,'Windy Bluff'),rect(-2,-71,3,4,5,'Sunset Ledge'),rect(0,-85,4,6,7,'Ranger Refuge')],obstacles:[],springs:[],sky:0xe3b48e},
 {id:'rooftops',name:'Midnight Rooftops',type:'rooftops',tag:'VERTICAL HOPS & SPRINGS',description:'Climb city roofs, hop the alleys and use glowing spring pads.',hint:'Gold pads launch you upward. Your second jump still gives three seconds of flight.',surfaces:[rect(0,0,0,6,6),rect(3,-14,1.5,5,5),rect(-3,-28,3,5,5),rect(3,-42,2,4.5,5),rect(-3,-56,4,5,5),rect(2,-70,5.5,5,5),rect(0,-85,6,6,6)].map((s,i)=>({...s,name:['Laundry Roof','Neon Crossing','Boiler House','Moonwalk','Spring Terrace','The Lookout','Penthouse Paws'][i]})),obstacles:[],springs:[{island:2,x:-3,z:-31},{island:4,x:-3,z:-59}],sky:0x252e4c}
];
export function contains(s,x,z,margin=0){return s.rx!==undefined?Math.abs(x-s.x)<s.rx-margin&&Math.abs(z-s.z)<s.rz-margin:Math.hypot(x-s.x,z-s.z)<s.r-margin;}
