import './style.css';
import {Game,STEP,levels} from './game.js';
import {makeScene} from './scene.js';
const $=id=>document.getElementById(id);
const game=new Game();let view,muted=false,audio=null,toastUntil=0,last=0,accumulator=0,visualTime=0;
const keys=new Set(),jumpPointers=new Set();let joyPointer=null,joy={x:0,z:0};
function fail(error){game.mode='error';$('error').hidden=false;$('errorText').textContent='This game needs a browser with WebGL 2 enabled. '+error.message;console.error(error);}
try{view=makeScene($('world'),game);}catch(error){fail(error);}
function unlock(){try{audio??=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume().catch(()=>{});}catch{}}
function note(hz,duration=.12,delay=0){if(muted||!audio||audio.state!=='running')return;const now=audio.currentTime+delay,o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.setValueAtTime(hz,now);g.gain.setValueAtTime(0,now);g.gain.linearRampToValueAtTime(.06,now+.008);g.gain.exponentialRampToValueAtTime(.001,now+duration);o.connect(g);g.connect(audio.destination);o.start(now);o.stop(now+duration+.01);o.onended=()=>{o.disconnect();g.disconnect();};}
function sound(type){const notes={jump:[330],fly:[523,659,784],fish:[1047],kitten:[523,659,784,1047],spring:[330,659,988],checkpoint:[440,659],hurt:[110,80],bonk:[220,330],win:[523,659,784,1047,1318]}[type];notes?.forEach((n,i)=>note(n,.15,i*.075));}
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');toastUntil=performance.now()+3200;}
function clearInput(){keys.clear();joy={x:0,z:0};joyPointer=null;jumpPointers.clear();$('stick').style.transform='';}
function updateHud(){const p=game.player;$('hearts').textContent='♥ '.repeat(game.hearts)+'♡ '.repeat(3-game.hearts);$('hearts').setAttribute('aria-label',`${game.hearts} hearts`);$('fish').textContent=game.fish;$('kittens').textContent=`${game.rescued} / 3`;$('flightTime').textContent=p.flight.toFixed(1)+'s';$('flightLabel').textContent=p.flying?'FLYING':p.spent?'LAND TO REFILL':'WINGS READY';$('fuel').style.transform=`scaleX(${p.flight/3})`;$('jumpText').textContent=p.flying?'RISE':!p.grounded&&!p.spent?'FLY':'JUMP';$('jumpHint').textContent=p.flying?'RELEASE TO GLIDE':p.spent?'LAND TO REFILL':'TAP AGAIN TO FLY';$('zone').textContent=game.surfaces[game.checkpoint].name.toUpperCase();$('levelName').textContent=`0${game.levelIndex+1} / ${game.level.name.toUpperCase()}`;}
function start(index=game.levelIndex){clearInput();unlock();game.start(index);const renderer=view.renderer;view.dispose();view=makeScene($('world'),game,renderer);$('quality').textContent='HQ';$('levelPicker').hidden=true;document.body.dataset.theme=game.level.type;$('menu').hidden=true;$('dialog').hidden=true;$('hud').hidden=false;$('controls').hidden=false;document.body.classList.add('playing');last=0;accumulator=0;toast(game.level.hint);updateHud();}
function dialog(title,text,button,eyebrow){clearInput();$('dialogTitle').textContent=title;$('dialogText').textContent=text;$('resume').textContent=button;$('dialogEyebrow').textContent=eyebrow;$('dialog').hidden=false;$('controls').hidden=true;}
function pause(){if(game.mode!=='playing')return;game.mode='paused';dialog('A little cat nap.','Your adventure is right where you left it.','Keep exploring ↗','TAKE A BREATHER');$('pause').setAttribute('aria-label','Resume game');}
function resume(){unlock();if(game.mode==='won'){if(game.levelIndex<levels.length-1)start(game.levelIndex+1);else openLevels();return;}if(game.mode==='lost')game.retry();else game.mode='playing';clearInput();$('dialog').hidden=true;$('controls').hidden=false;$('pause').setAttribute('aria-label','Pause game');last=0;accumulator=0;}
function processEvents(){for(const e of game.events){sound(e.type);if(['fish','kitten','bonk'].includes(e.type))view.burst(e.x,e.y,e.z,e.type==='kitten'?0xa8d6a0:0xffd889);if(e.type==='kitten')toast(`${e.name} is safe! ${game.rescued===3?'Everyone’s together. Head to Cat Haven!':`${3-game.rescued} kittens still need you.`}`);if(e.type==='checkpoint')toast('Checkpoint saved · '+e.name);if(e.type==='spring')toast('Spring launch! Tap jump in the air to spread your wings.');if(e.type==='empty')toast('Wings tired. Land to recharge.');if(e.type==='missing')toast(`Find ${3-game.rescued} more kitten${game.rescued===2?'':'s'} before going home. You can fly back.`);if(e.type==='hurt'&&game.mode!=='lost')toast('Back on your paws. Checkpoint restored.');}
 game.events.length=0;if(game.mode==='lost'&&$('dialog').hidden)dialog('A rough landing.','Your rescued kittens and fish are safe. Try again from your last checkpoint.','Try checkpoint ↗','STILL A BRAVE LITTLE CAT');if(game.mode==='won'&&$('dialog').hidden){const seconds=Math.floor(game.time),mins=Math.floor(seconds/60);dialog('Everybody’s home.',`Three kittens rescued. ${game.fish} fish collected. ${mins}:${String(seconds%60).padStart(2,'0')} of sky-high trouble.`,game.levelIndex<levels.length-1?'Next level ↗':'Choose a level ↗',game.level.name.toUpperCase()+' COMPLETE');}}
let pickerReturn='menu';
function openLevels(){pickerReturn=game.mode;clearInput();game.mode='paused';$('menu').hidden=true;$('dialog').hidden=true;$('controls').hidden=true;$('levelPicker').hidden=false;}
function closeLevels(){game.mode=pickerReturn;$('levelPicker').hidden=true;$('menu').hidden=pickerReturn!=='menu';$('dialog').hidden=!['paused','lost','won'].includes(pickerReturn);$('controls').hidden=pickerReturn!=='playing';last=0;accumulator=0;}
levels.forEach((level,index)=>{const button=document.createElement('button');button.className='level-card '+level.type;button.dataset.level=index;button.innerHTML=`<small>0${index+1} · ${level.tag}</small><strong>${level.name}</strong><span>${level.description}</span><b>PLAY LEVEL ↗</b>`;button.onclick=()=>start(index);$('levelCards').append(button);});
$('levelsButton').onclick=openLevels;$('chooseLevel').onclick=openLevels;$('dialogLevels').onclick=openLevels;$('closeLevels').onclick=closeLevels;
const movement=new Set(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space']);
addEventListener('keydown',e=>{if(e.code==='Escape'||e.code==='KeyP'){if(!e.repeat){if(!$('levelPicker').hidden){closeLevels();return;}game.mode==='playing'?pause():game.mode==='paused'?resume():null;}return;}if(!movement.has(e.code)||game.mode!=='playing')return;e.preventDefault();if(e.code==='Space'&&!keys.has('Space')){unlock();game.jump();}keys.add(e.code);});
addEventListener('keyup',e=>keys.delete(e.code));
function joystickMove(e){if(e.pointerId!==joyPointer)return;const r=$('joystick').getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,len=Math.hypot(dx,dy),max=r.width*.32,scale=len>max?max/len:1;joy={x:dx*scale/max,z:dy*scale/max};$('stick').style.transform=`translate(${dx*scale}px,${dy*scale}px)`;}
$('joystick').addEventListener('pointerdown',e=>{if(game.mode!=='playing'||joyPointer!==null)return;e.preventDefault();joyPointer=e.pointerId;$('joystick').setPointerCapture(e.pointerId);joystickMove(e);});$('joystick').addEventListener('pointermove',joystickMove);
function joyEnd(e){if(e.pointerId===joyPointer){joyPointer=null;joy={x:0,z:0};$('stick').style.transform='';}}
for(const event of ['pointerup','pointercancel','lostpointercapture'])$('joystick').addEventListener(event,joyEnd);
$('jump').addEventListener('pointerdown',e=>{if(game.mode!=='playing')return;e.preventDefault();unlock();if(!jumpPointers.size)game.jump();jumpPointers.add(e.pointerId);$('jump').setPointerCapture(e.pointerId);});for(const event of ['pointerup','pointercancel','lostpointercapture'])$('jump').addEventListener(event,e=>jumpPointers.delete(e.pointerId));
// Allow assistive technologies to activate the same button without a pointer.
$('jump').addEventListener('click',e=>{if(e.detail===0){unlock();game.jump();}});
$('start').onclick=()=>start();$('restart').onclick=()=>start();$('resume').onclick=resume;$('pause').onclick=()=>{if(!$('levelPicker').hidden){closeLevels();return;}game.mode==='paused'?resume():pause();};$('sound').onclick=()=>{muted=!muted;$('sound').textContent=muted?'♪̸':'♫';$('sound').setAttribute('aria-label',muted?'Enable sound':'Mute sound');$('sound').setAttribute('aria-pressed',String(muted));if(!muted){unlock();note(659);}};
$('quality').onclick=()=>{const high=view.setQuality();$('quality').textContent=high?'HQ':'LQ';toast(high?'High quality visuals':'Low power mode · fewer pixels, no shadows');};
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{toast('Fullscreen is unavailable here. Try turning your phone sideways.');}};
addEventListener('blur',()=>{clearInput();pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();pause();}last=0;accumulator=0;});addEventListener('resize',()=>view?.resize());addEventListener('contextmenu',e=>{if(e.target.closest('#controls'))e.preventDefault();});
$('world').addEventListener('webglcontextlost',e=>{e.preventDefault();pause();$('error').hidden=false;$('errorText').textContent='The graphics connection was interrupted. Reload to start again.';});
function frame(t){if(!view||game.mode==='error')return;const dt=last?Math.min((t-last)/1000,.08):0;last=t;if(!document.hidden){if(game.mode==='playing'){const input={x:joy.x+(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0),z:joy.z+(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0),rise:keys.has('Space')||jumpPointers.size>0};accumulator+=dt;while(accumulator>=STEP){game.step(STEP,input);accumulator-=STEP;}processEvents();updateHud();}else accumulator=0;if(game.mode!=='paused'&&game.mode!=='lost')visualTime+=dt;view.render(game.mode==='paused'?0:dt,visualTime);if(t>toastUntil)$('toast').classList.remove('visible');}requestAnimationFrame(frame);}
if(location.hash==='#test')window.__asscat={game,start,pause,resume,get view(){return view;},get input(){return{joy,keys:[...keys],jump:jumpPointers.size}}};
requestAnimationFrame(frame);
